## Model & Training Configuration
model_checkpoint: "PekingU/rtdetr_v2_r18vd"
image_size: 480

## Dataset paths (use forward slashes for cross‑platform compatibility)
train_images_dir: "datasets/train"
train_annotations: "datasets/train.json"
val_images_dir: "datasets/val"
val_annotations: "datasets/val.json"

## Training hyperparameters
num_epochs: 40
learning_rate: 5e-5
batch_size: 8
early_stopping_patience: 3
map_threshold: 0.01

## Trainer settings
metric_for_best_model: "eval_loss"
greater_is_better: true
load_best_model_at_end: true
eval_strategy: "epoch"
save_strategy: "epoch"
save_total_limit: 2
remove_unused_columns: false
report_to: "tensorboard"

## Logging & checkpoints
log_dir: "logs/"
save_dir: "checkpoints/"
